[[rules]]
name = "whitespace"
color = "aqua"
regex = '[ \t\n\f]+'

[[rules]]
name = "string"
color = "yellow"
regex = '"([^"\\]|\\.)*"'

[[rules]]
name = "block_comment"
color = "yellow"
regex = '/\*[\s\S]*?\*/'

[[rules]]
name = "line_comment"
color = "yellow"
regex = '//[^\n]*'
