[[tokens]]
name = "whitespace"
color = "aqua"
regex = '[ \t\n\f]+'

[[tokens]]
name = "string"
color = "yellow"
regex = '"([^"\\]|\\.)*"'

[[tokens]]
name = "block_comment"
color = "yellow"
regex = '/\*[\s\S]*?\*/'

[[tokens]]
name = "line_comment"
color = "yellow"
regex = '//[^\n]*'

[[rules]]
before = ""
action = ""
after = ""
