[[tokens]]
name = "whitespace"
color = "aqua"
regex = '[ \t\n\f]+'

[[tokens]]
name = "string"
color = "yellow"
regex = '"([^"\\]|\\.)*"'

[[tokens]]
name = "block_comment"
color = "yellow"
regex = '/\*[\s\S]*?\*/'

[[tokens]]
name = "line_comment"
color = "yellow"
regex = '//[^\n]*'

[[tokens]]
name = "open_paren"
color = "yellow"
regex = '\('

[[tokens]]
name = "close_paren"
color = "yellow"
regex = '\)'

[[rules]]
before = "open_paren"
action = ""
after = "close_paren"

[[rules]]
before = "close_paren"
action = " "
after = "any"

[[rules]]
before = "any"
action = " "
after = "open_paren"
